-- 本次变更：补齐中间表缺失的审计字段
-- 执行时间：2026-06-27
-- 适用场景：已存在的历史数据库（从旧版本升级）
-- 注意：如果某列已存在，对应语句会报错，请根据实际情况跳过

ALTER TABLE sys_permission
    ADD COLUMN create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    ADD COLUMN update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE sys_user_role
    ADD COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除',
    ADD COLUMN create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    ADD COLUMN update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE sys_role_permission
    ADD COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除',
    ADD COLUMN create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    ADD COLUMN update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
